# Makefile for tinymce
all: tinymce

tinymce:
	wget http://github.com/downloads/tinymce/tinymce/tinymce_3.4.9_jquery.zip
	unzip tinymce_3.4.9_jquery.zip
	mv tinymce/jscripts/tiny_mce static/js
	rm -rf tinymce_3.4.9_jquery.zip tinymce
