# Default tool config file. See also setup.cfg for tools that don't yet
# support pyproject.toml.

[tool.black]
line-length = 88
target_version = ['py37']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | __pycache__
  | buck-out
  | build
  | dist
  | node_modules
  | baseframe/static
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 88
order_by_type = true
use_parentheses = true
from_first = true
known_future_library = ['__future__']
known_first_party = ['baseframe', 'coaster', 'flask_lastuser']
known_sqlalchemy = [
  'alembic',
  'sqlalchemy',
  'sqlalchemy_utils',
  'flask_sqlalchemy',
  'psycopg2'
]
known_flask = [
  'flask',
  'werkzeug',
  'markupsafe',
  'itsdangerous',
  'wtforms',
  'wtforms_sqlalchemy',
  'webassets',
  'flask_assets',
  'flask_babel',
  'flask_flatpages',
  'flask_mail',
  'flask_migrate',
  'flask_rq2',
  'flask_wtf',
  ]
default_section = 'THIRDPARTY'
sections = [
  'FUTURE',
  'STDLIB',
  'SQLALCHEMY',
  'FLASK',
  'THIRDPARTY',
  'FIRSTPARTY',
  'LOCALFOLDER'
]

[tool.mypy]
files = '**/*.py'
exclude = 'node_modules'
plugins = ['sqlmypy']
ignore_missing_imports = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true
warn_redundant_casts = false
check_untyped_defs = false

[tool.pylint.master]
load-plugins = ['pylint_pytest', 'pylint_flask_sqlalchemy']
# max-parents = 10
init-hook = """
import os, astroid.bases, pathlib
# Tell Pylint where to find packages from within tests
for path in pathlib.Path.cwd().parents:
    if (path / 'pyproject.toml').is_file():
      sys.path.append(str(path))
"""

[tool.pylint.message_control]
max-line-length = 88
disable = [
  'cyclic-import',  # We have tail imports all over
  'fixme',  # Our workflow is to tag for future fixes
  'invalid-name',  # Flake8 covers our naming convention requirements
  'missing-class-docstring',  # Backlog
  'missing-function-docstring',  # Backlog
  'no-member',  # Pylint doesn't understand mixins referring to main class members
  'redefined-builtin',  # Covered by Flake8 already
  'too-few-public-methods',  # Data classes and validator classes have few methods
  'too-many-arguments',
  'too-many-branches',
  'too-many-locals',
  'too-many-instance-attributes',  # Some instances are just bags of attributes
  'too-many-lines',
  'too-many-nested-blocks',
  'too-many-return-statements',
  'too-many-statements',
  'unused-argument',  # Arguments required for spec compatibility aren't always used
  'wrong-import-position',  # Imports after code are sometimes required
  'wrong-import-order',  # Let black and isort handle this
]

[tool.bandit]
exclude_dirs = ['node_modules']

[tool.bandit.assert_used]
skips = ['*/*_test.py', '*/test_*.py']
