name: Pytest

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths:
      - '**.py'
      - '**.js'
      - '**.jinja2'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.10']

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: |
          pip install 'git+https://github.com/hasgeek/coaster'
          pip install -e .
          pip install -r test_requirements.txt
      - name: Install pytest-github-actions-annotate-failures
        run: pip install pytest-github-actions-annotate-failures
      - name: Test with pytest
        run: |
          pytest --showlocals --cov=baseframe
      - name: Prepare coverage report
        run: |
          mkdir -p coverage
          coverage lcov -o coverage/vaseframe.lcov
      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/baseframe.lcov
          flag-name: python-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/baseframe.lcov
          parallel-finished: true
